import React from 'react'
import Head from 'next/head'

export default function RootLayout ({ children, title = 'Next 13' }: {children :React.ReactElement | React.ReactElement[], title?: string}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      {children}
    </>
  )
}
